name: "Form-Replacements"
exports: "form-replacements.js"
web: "[portfolio.bryanjswift.com](http://portfolio.bryanjswift.com)"
description: "Creates styleable elements that function like standard form elements."
license: "[MIT License](http://mootools.net/license.txt)"
copyright: "&copy; [Bryan J Swift](http://portfolio.bryanjswift.com)"
author: "bryanjswift"
authors: "[Bryan J Swift](http://portfolio.bryanjswift.com)"
docs: http://bryanjswift.github.com/mootools-form-replacements
demos: http://bryanjswift.github.com/mootools-form-replacements
category: Forms
tags: [styleable, select, checkbox, radio]
sources:
    - "Source/Form.Check.js"
    - "Source/Form.CheckGroup.js"
    - "Source/Form.Radio.js"
    - "Source/Form.RadioGroup.js"
    - "Source/Form.SelectOption.js"
    - "Source/Form.Dropdown.js"